### ISSUE TITLE
Error when using /email

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#36]
Hi,
first off there is no error for this when using debug-mode in console.
Ingame it says:
Error - commands-email-1.2.jar not found in plugins /CommandsEX, to use /email functions please add commons-email-1.2.jar
Did i miss to download another plugin first?

**Comment by keir-nellyer** [comment]
You have to copy all the jar files that are in the CommandsEX folder from the zip file you got from BukkitDev or the Builder and add it into the CommandsEX folder in the plugins folder.

**Comment by ghost** [comment]
I am using the builder version but there is no commons-email-1.2.jar in the CommandsEX zip and the folder in plugins. There is just a mail.jar in the plugins/CommandsEx folder. I also tried to rename this jar to the one above but then it gives another error and tells me to redownload it or contact you.
I tried the builder version with all selected too - no commons-email.
The link to the full version you wrote in the comments on Bukkit dev is broken.

**Comment by keir-nellyer** [comment]
Ah, try renaming the file mail.jar in the CommandsEX folder to commons-email-1.2.jar. This is a typo in the code and I'll fix this shortly.

I currently can't send my changes to GitHub because I don't have my new Jenkins setup.

**Comment by ghost** [comment]
I already tried renaming it but it does not work as i said above. But no problem it can wait a few days.

**Comment by keir-nellyer** [comment]
Ah I see the issue, one bit of code says to look at commons-email-1.2.jar and the other says look at mail.jar. Create a copy of mail.jar and rename it to commons-email-1.2.jar. I'll get this fixed for the next version but for now you will have to have 2 copies of the jar.

**Comment by ghost** [comment]
Nope it doesn´t work. I did what you said but i am getting the same error as before.
It tells me again that there is an error with the jar and that i have to redownload commons-email-1.2.jar or to contact you.

**Comment by keir-nellyer** [comment]
Ok so there are multiple issues going on here and one of them is to do with the builder. Please create a new copy from the builder and then create a copy of commons-email-1.2.jar and rename that copy to mail.jar. They should load now.

**Comment by ghost** [comment]
I am getting an error after i replaced the folder and the CommandsEX.jar file with the new one from the builder:
Log:
2013-02-10 18:53:36 [SEVERE] Could not load 'plugins\CommandsEX.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:260)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:132)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:257)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:235)
    at gm.<init>(ServerConfigurationManager.java:121)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:140)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:722)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: while parsing a block mapping
 in "<reader>", line 1, column 1:
    authors: [iKeirNez, kezz101, Jno ... 
    ^
expected <block end>, but found BlockMappingStart
 in "<reader>", line 113, column 3:
      cex_amessage:
      ^

```
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:575)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:42)
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:255)
... 8 more
```

**Comment by keir-nellyer** [comment]
Sorry about that. Should be fixed now. java, php and yaml don't go too well together. Unfortunately you will have to re-download it again and follow the steps in my last comment again.

**Comment by ghost** [comment]
Sorry but after testing it /email still does not work and tells me the "redownload" message.

**Comment by keir-nellyer** [comment]
Sorry this is taking so long, have you created the commons-email-1.2.jar file and mail.jar file in the CommandsEX folder in the plugins folder?

Are you still getting errors? Please re-paste them because they may have changed.

**Comment by ghost** [comment]
I kopied the commons-email-1.2.jar and renamed it to mail.jar => both jars in the cex folder.
There is no console error (debugmode is true).
Just in the chat again:
"There was an error loading commons-email-1.2.jar, please try to redownload this file or alert the authors of CommandsEX."

Please take your time with this issue. I do not necessary need the /email command atm. Only the other commands are really important and they work fine.

**Comment by keir-nellyer** [comment]
Can you please upload your jar somewhere so I can take a look at it.

**Comment by ghost** [comment]
commons-email jar:
http://www.file-upload.net/download-7190313/commons-email-1.2.jar.html
cex jar:
http://www.file-upload.net/download-7190319/CommandsEX.jar.html

Please write a comment when i can delete the links.

**Comment by keir-nellyer** [comment]
Its the CommandsEX.jar I need, it says it was deleted. You can email it to me keir@nellyer.co.uk

**Comment by keir-nellyer** [comment]
Ok, I uploaded some more fixes to the Builder. Please try that and let me know. I'm currently unable to test myself. In this version you only need to have to commons-email-1.2.jar, you don't need to create the copy

**Comment by keir-nellyer** [comment]
Also if you see any errors, let me know.

**Comment by ghost** [comment]
This error happens when i start my server:
2013-02-11 15:28:11 [INFO] [CommandsEX] Enabling CommandsEX v2.1 DEV
2013-02-11 15:28:11 [WARNING] Unable to load locale en, trying English
2013-02-11 15:28:11 [INFO] Message: Can't find bundle for base name lang, locale en, cause: java.lang.NullPointerException
2013-02-11 15:28:11 [SEVERE] Error occurred while enabling CommandsEX v2.1 DEV (Is it up to date?)
java.util.MissingResourceException: Can't find bundle for base name lang, locale en
    at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
    at java.util.ResourceBundle.getBundleImpl(Unknown Source)
    at java.util.ResourceBundle.getBundle(Unknown Source)
    at com.github.zathrus_writer.commandsex.Language.init(Language.java:51)
    at com.github.zathrus_writer.commandsex.CommandsEX.onEnable(CommandsEX.java:125)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:427)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:300)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:282)
    at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:600)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:566)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:445)
    at ho.c(DedicatedServer.java:195)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:722)
    at fy.run(ThreadMinecraftServer.java:16)

And this one when i try to use /email <player> <message>
2013-02-11 15:34:51 [WARNING] Unable to load locale en, trying English
2013-02-11 15:34:51 [INFO] Message: Can't find bundle for base name lang, locale en, cause: null
2013-02-11 15:34:51 [WARNING] Missing translation of 'emailErrorLoadingJar' for language 'en'

**Comment by keir-nellyer** [comment]
Fixed see #38

**Comment by keir-nellyer** [comment]
Let me know if email works now too!

**Comment by ghost** [comment]
All /tp commands and /amessage work fine now. no errors.
But i have got to say that /email still does not work. It says again Error with the commons-email-1.2.jar in chat and no error in console.

**Comment by keir-nellyer** [comment]
Turns out this was an issue with the Builder adding the code to the wrong place. You will be glad to know it now works (confirmed myself).
